### ISSUE TITLE
LDAP Sync is broken

### ISSUE THREAD

**Issue by kuboschek** [OpenJUB/dreamjub#1]
Running `manage.py ldapsync` fails with an ImportError. Even after fixing said error, more errors come up.

Expected Result:
Student instances are updated from LDAP in the local database

Actual Result:
`ImportError`

Steps to reproduce:
run `manage.py ldapsync` in the project root folder

**Comment by thunderboltsid** [comment]
Here's the stack trace that I get:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/siddharthshukla/OpenJUB/dreamjub/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/siddharthshukla/OpenJUB/dreamjub/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/siddharthshukla/OpenJUB/dreamjub/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/siddharthshukla/OpenJUB/dreamjub/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/siddharthshukla/OpenJUB/dreamjub/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/siddharthshukla/OpenJUB/dreamjub/dreamjub/management/commands/ldapsync.py", line 2, in <module>
    from jDREAM.models import Student
ImportError: No module named 'jDREAM'
```

I guess this is because jDREAM module does not exist and has been renamed to dreamjub.
